apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: helloworld-pod
  template:
    metadata:
      labels:
        pod: helloworld-pod
    spec:
      containers:
      - name: helloworld-container
        image: helloworld:latest
        imagePullPolicy: Never
